services:
  - type: web
    name: crm-backend
    env: node
    buildCommand: npm install
    startCommand: npm run build && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health